### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by punmechanic** [zedgu/ovenware#4]
Hi, 

`loader.js` only allows for `.js` files to be loaded. Consider removing the path extension restriction and removing the extension based on `path.extname`:

``` javascript
    if (fs.statSync(file).isFile()) {
      var filePath = '^' + path.join(path.resolve(root), '/');
      var ext = path.extname(file);
      filePath = filePath.replace(/\\/g, '\\\\');
      paths[file.replace(new RegExp(filePath), '').replace(ext, '').toLowerCase()] = file;

```

**Comment by zedgu** [comment]
what's the extname of coffeescript ?
i don't think we should load all format files, except js.

**Comment by punmechanic** [comment]
@zedgu coffeescript can be in `.coffee`, `.litcoffee`, `.md.coffee`, probably a few others
I think it at the very least makes sense to leave it up to the user of the package to decide what they want to load.

**Comment by zedgu** [comment]
new option api for extname , checkout v0.2.2
